modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU General Public License v3.0"

[[mods]]
modId = "moneyboymod"
version = "${version}"
displayName = "Moneyboys Mod"
authors = "MrJulsen, MrPatty, PULZ418"
displayUrl = "https://github.com/MisterJulsen/MoneyBoyMod"
issueTrackerURL = "https://github.com/MisterJulsen/MoneyBoyMod/issues"
description = '''
Money! Money! Money!
'''
logoFile = "icon.png"

[[dependencies.moneyboymod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moneyboymod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moneyboymod]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
